### //TRAER TODOS LOS USUARIOS
GET http://localhost:3000/users

###// BUSCAR UN USUARIO POR ID
GET http://localhost:3000/users/67b0689ce0cbb563db46f3a2
###//MODIFICAR UN USUARIO
PATCH http://localhost:3000/users/67b095daf91247f4fda8da5e
Content-Type: application/json

{

    "email":"juan@mail.com"

}

###//AGREGAR UN USUARIO
POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Sofia",
    "email":"sofia@mail.com",
    "age":50
}

###
DELETE  http://localhost:3000/users/67b068d4e0cbb563db46f3a7