openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: API for managing users

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        200:
          description: Successfully retrieved all users
          content:
            application/json:
              example:
                [
                  {
                    "id": "db5d8968b9c64719-964e-2df6ffb22b5b",
                    "name": "David",
                    "email": "david@mail.com",
                    "age": 30,
                  },
                  {
                    "id": "b8cbec7d1b404906b8be56145e64e9ae",
                    "name": "Sara",
                    "email": "sara@mail.com",
                    "age": 45,
                  },
                ]
        500:
          description: Internal Server Error
        404:
          description: No users found

    post:
      tags:
        - Users
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                age:
                  type: number
      responses:
        201:
          description: Successfully created user
          content:
            application/json:
              example:
                { "name": "Alice", "email": "alice@example.com", "age": 27 }
        400:
          description: Bad Request - Invalid input data
        500:
          description: Internal Server Error

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      responses:
        200:
          description: Successfully retrieved user
          content:
            application/json:
              example:
                {
                  "id": "b6426148001d-4381a808-e3cdbbfc122f",
                  "name": "Maria",
                  "email": "maria@mail.com",
                  "age": 25,
                }
        404:
          description: User not found
        500:
          description: Internal Server Error

    patch:
      tags:
        - Users
      summary: Update user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                age:
                  type: number
      responses:
        200:
          description: Successfully updated user
          content:
            application/json:
              example: { "name": "Juan", "email": "juan@mail.com", "age": 52 }
        400:
          description: Bad Request - Invalid input data
        404:
          description: User not found
        500:
          description: Internal Server Error

    delete:
      tags:
        - Users
      summary: Delete user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      responses:
        200:
          description: Successfully deleted user
          content:
            application/json:
              example: { "message": "Successfully deleted user" }
        404:
          description: User not found
        500:
          description: Internal Server Error
